#!/usr/bin/env bash

file="/home/david/Desktop/ALX_RESOURCES/alx-system_engineering-devops/0x05/PRACTICE/file.txt"
trap "rm -f $file; exit" 0 2 15

echo "pid is $$"
while (( COUNT < 10 ))
do
	sleep 10
	(( COUNT ++ ))
	echo $COUNT
done
exit 0
