#!/usr/bin/env bash
# A script that transfers a file from our client to a server
# Accepts 4 arguments

if [ "$#" -eq 4 ]
then
    scp -i "$4" -o "StrictHostKeyChecking=no" "$1" "$3"@"$2":'~/'
else [ "$#" -eq 4 ]
    echo "Usage: 0-tansfer_file PATH_TO_FILE IP USERNAME PATH_TO_SSH_KEY"
fi
