#!/usr/bin/env bash
# A script that installs nginx web server and configures a 404 error page

# update package list from the repositories
sudo apt-get -y update

# install nginx server
sudo apt-get -y install nginx

# write to the html file
echo "Hello World!" | sudo tee /var/www/html/index.html

# configured a permanent redirect and 404 error page
echo "server {
   listen 80 default_server;
   listen [::]:80 default_server;
   
   root /var/www/html;
   index index.html;
   location / {
   }
   rewrite ^/redirect_me https://www.youtube.com/watch?v=QH2-TGUlwu4 permanent;
}" > default

# move to /etc/nginx/sites-available/default
sudo mv -f default /etc/nginx/sites-available/default

# restart nginx server to effect changes
sudo service nginx restart
