#!/usr/bin/env bash
# A script that installs nginx web server and configures a permanent redirect

# update package list from the repositories
sudo apt-get -y update

# install nginx server
sudo apt-get -y install nginx

# write to the html file
echo "Hello World!" | sudo tee /var/www/html/index.html

# move to the /etc/nginx/sites-available/ directory
cd /etc/nginx/sites-available/ || exit

# configure a permanent redirect
str='server_name_;\n\trewrite ^\/redirect_me https:\/\/www.youtube.com\/watch?v=QH2-TGUlwu4 permanent;'

# replace it in the default file
sudo sed -i "s/server_name_;/$str/" default

# restart nginx server to effect changes
sudo service nginx restart
