#!/usr/bin/env bash
# A script that installs nginx web server and configures a 404 error page

# update package list from the repositories
sudo apt-get -y update

# install nginx server
sudo apt-get -y install nginx

# write to the html file
echo "Hello World!" | sudo tee /var/www/html/index.html

# move to the /etc/nginx/sites-available/ directory
cd /etc/nginx/sites-available/ || exit

# write to the html file
echo "Ceci n'est pas une page" | sudo tee /var/www/html/404_page.html

# remove default
sudo rm -f default

# configured a permanent redirect and 404 error page
echo "server {
   listen 80 default_server;
   listen [::]:80 default_server;
   
   root /var/www/html;
   index index.html;
   location / {
      try_files $uri/ =404;
   }
   rewrite ^/redirect_me https://www.youtube.com/watch?v=QH2-TGUlwu4 permanent;
   error_page 404 /404_page.html;
   location = /404_page.html{
      root /var/www/html;
      internal;
   }
}" > default
# replace it in the default file
#sudo sed -i "s/server_name_;/$str_404/" default

# restart nginx server to effect changes
sudo service nginx restart
