#!/usr/bin/env bash
# A script that installs nginx web server and configures a 404 error page

# update package list from the repositories
sudo apt-get -y update

# install nginx server
sudo apt-get -y install nginx

# write to the html file
echo "Hello World!" | sudo tee /var/www/html/index.html

# configure a permanent redirect
str_404='server_name_;\n\terror_page 404 \/404.html;\n\tlocation = /404.html {\n\t\troot /var/www/html;\n\t\tinternal;\n\t}'

# move to the /etc/nginx/site-available/ directory
cd /etc/nginx/site-available/

# replace it in the default file
sed -i "s/server_name_;/$str_404/" default

# restart nginx server to effect changes
sudo service nginx restart
