#!/usr/bin/env bash
# A script that installs nginx web server
# configures a redirect
# configures a 404 error page
# configures a custom header

# update package list from the repositories
sudo apt-get -y update

# install nginx server
sudo apt-get -y install nginx

# write to the html file
echo "Hello World!" | sudo tee /var/www/html/index.html

# write to the html file
echo "Ceci n'est pas une page" | sudo tee /var/www/html/404_page.html

# configured a permanent redirect and 404 error page
echo "server {
   listen 80 default_server;
   listen [::]:80 default_server;
   
   root /var/www/html;
   index index.html;
   location / {
    add_header X-Served_By $HOSTNAME;
   }
   rewrite ^/redirect_me https://www.youtube.com/watch?v=QH2-TGUlwu4 permanent;
   error_page 404 /404_page.html;
   location = /404_page.html{
      root /var/www/html;
      internal;
   }
}" > default
sudo mv -f default /etc/nginx/sites-available/default

# restart nginx server to effect changes
sudo service nginx restart
