#!/usr/bin/env bash
# configures an nginx server to listen on port 80 and respond regardless of process stop
sudo cp /etc/nginx/sites-available/default /etc/nginx/sites-enabled/default
sudo service nginx start
sudo kill -9 "$(cat /run/nginx.pid)"
