#!/usr/bin/env bash
# Process and PID file

echo "$$" > ./myscript.pid
trap "echo I hate the kill command; rm ./myscript.pid; exit" SIGTERM
trap "echo Y U no love me?!" SIGINT
trap "rm ./myscript.pid; exit" SIGQUIT

while :
do
	echo "To infinity and beyond"
	sleep 2
done
