#!/usr/bin/env bash
# FizzBuzz in bash
for i in {1..100}
do
	if  (( i % 3 == 0 )) &&  (( i % 5 == 0 ))
	then
	    echo "FizzBuzz"
	elif  (( i % 3 != 0 )) &&  (( i % 5 == 0 ))
	then
	    echo "Buzz"
	elif  (( i % 3 == 0 )) &&  (( i % 5 != 0 ))
	then
	    echo "Fizz"
	else
	    echo $i
	fi
done
