#!/usr/bin/env bash
# This script displays the time for 12 hours and 59 minutes.
hour=0
while (( hour<13 ))
do
	i=1
	echo "Hour: $hour"
	while (( i<60 ))
	do
		echo "$i"
		(( i++ ))
	done
	(( hour++ ))
done
