#!/usr/bin/env bash
# Resolves localhost ip to 127.0.0.2
# Resolves facebook.com ip to 8.8.8.8
sudo cp /etc/hosts ~/hosts.new
echo "127.0.0.2 localhost" > ~/hosts.new
echo "8.8.8.8	facebook" >> ~/hosts.new
sudo cp -f ~/hosts.new /etc/hosts
