#!/usr/bin/env bash
# Resolves localhost ip to 127.0.0.2
# Resolves facebook.com ip to 8.8.8.8
cp /etc/hosts ~/hosts.new
sed -i s/127.0.0.1/127.0.0.2/ ~/hosts.new
echo "8.8.8.8	facebook" >> ~/hosts.new
cp -f ~/hosts.new /etc/hosts
